version: '3.5'

services:
    crawlman:
        image: webrecorder/crawlman
        build:
            context: .
        environment:
            - REDIS_URL=redis://redis/0
            - DEFAULT_POOL=auto-pool

        depends_on:
            - redis
            - pywb

        ports:
            - 8000:8000

        volumes:
            - ./:/app/

    pywb:
        image: webrecorder/pywb

        command: ${PYWB_COMMAND_LINE}

        environment:
            - INIT_COLLECTION=coll

        volumes:
            - ./webarchive:/webarchive

        networks:
            - browsers

        ports:
            - 8180:8080

    shepherd:
        image: oldwebtoday/shepherd:1.1.0-dev

        environment:
            - BROWSER_NET=crawlmanager_browsers
            - MAIN_NET=crawlmanager_default

            - PROXY_HOST=pywb
            - PROXY_PORT=8080

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./flocks:/app/flocks

        ports:
            - 9020:9020

    redis:
        image: redis:3.2.4

    behaviors:
      image: webrecorder/behaviors


networks:
    default:
        driver: bridge

    browsers:
        driver: bridge

