version: '3.5'

services:
    browsertrix:
        image: webrecorder/browsertrix
        build:
            context: .
        environment:
            - REDIS_URL=redis://redis/0
            - DEFAULT_POOL=auto-pool
            - SCREENSHOT_API_URL=http://pywb:8080/api/screenshot/{coll}
            - EXTRACTED_RAW_DOM_API_URL=http://pywb:8080/api/dom/{coll}
            - PROXY_HOST=pywb

        depends_on:
            - redis
            - pywb

        ports:
            - 8000:8000

        volumes:
            - ./:/app/

    pywb:
        build: ./pywb/

        environment:
            - INIT_COLLECTION=coll
            - REDIS_URL=redis://redis/0

        volumes:
            - ./webarchive:/webarchive

        networks:
            - default
            - browsers

        ports:
            - 8180:8080

        depends_on:
            - redis

    solr:
        image: solr

        volumes:
          - ./solr:/var/solr

        entrypoint:
          - docker-entrypoint.sh
          - solr-precreate
          - browsertrix

        ports:
          - 8983:8983

    shepherd:
        image: oldwebtoday/shepherd:1.1.0-dev

        environment:
            - BROWSER_NET=browsertrix_browsers
            - MAIN_NET=browsertrix_default

            - PROXY_HOST=pywb
            - PROXY_PORT=8080

        depends_on:
            - redis

        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./flocks:/app/flocks
            - ./pool_config.yaml:/app/pool_config.yaml

        ports:
            - 9020:9020

    redis:
        image: redis:3.2.4

    behaviors:
      image: webrecorder/behaviors

      ports:
            - 3030:3030

networks:
    default:
        driver: bridge

    browsers:
        driver: bridge

